[update]
tasks = ["interfaces", "code", "transform", "translate", "normalize"]

[update.interfaces]
paths = ["./MastersPortal"]
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.code]
codePaths = ["./MastersPortal"]
localizablePaths = ["./MastersPortal"]
defaultToKeys = false
additive = true
unstripped = false
plistArguments = true

[update.transform]
codePaths = ["./MastersPortal"]
localizablePaths = ["./MastersPortal"]
transformer = "swiftgenStructured"
supportedLanguageEnumPath = "./MastersPortal/Resources/Localization"
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
paths = ["./MastersPortal"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[update.translate]
paths = "./MastersPortal"
secret = "f5ad935c1d82473eb0eb558c07d9e31a"
sourceLocale = "en"

[lint]
paths = ["./MastersPortal"]
duplicateKeys = true
emptyValues = true
