# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Ensure that your git status is not dirty
    ensure_git_status_clean
  
    # Increment the build number (not the version number)
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "MastersPortal.xcodeproj"
    )
    
    build_app(workspace: "MastersPortal.xcworkspace", scheme: "MastersPortal")

    # Commit the version bump
    commit_version_bump(xcodeproj: "Example.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote

    changelog_from_git_commits(merge_commit_filtering: 'exclude_merges')

    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
